### ISSUE TITLE
Extra properties should be removed from response

### ISSUE THREAD

**Issue by derolf** [Eywek/typoa#10]
Best to explain with an example

```Typescript
import { Controller, Get, Route } from "typoa";

interface TestResponse {
  foo: string;
}

@Route("test")
export class TestController extends Controller {
  @Get()
  public async getTest(): Promise<TestResponse> {
    const data = { foo: "bar", hidden: "hidden" };
    return data;
  }
}
```

Reponse from `GET /test`:

```JSON
{"foo":"bar","hidden":"hidden"}
```

I would expect:

```JSON
{"foo":"bar"}
```

**Comment by derolf** [comment]
What I am asking for is basically the "dual" of "validateAndParse" for responses.

**Comment by derolf** [comment]
@Eywek I am looking to a PR for this feature. What code formatter do you use?

**Comment by Eywek** [comment]
Hi,

Thank you for the suggestion.
You could try to implement it behind a feature flag, we're using tslint currently

**Comment by derolf** [comment]
I mean which code formatter do you use? I could not find a prettier config…

**Comment by Eywek** [comment]
> I mean which code formatter do you use? I could not find a prettier config…

I don't use a specific code formatted. Only tslint.

**Comment by derolf** [comment]
I am working on the PR (not finished yet) and get some formatting issues: https://github.com/derolf/typoa/commit/13fc30a9bdecb83a4adfa48df155cee113b258cc#diff-da4d3d3a97b9ed26e47b50d9a5d2f5795434467e001f8a6deba72c361a23baa7L13

I am using the "vanilla" Visual Code formatter. Do you have any special settings you can share?
