### ISSUE TITLE
Oauth security

### ISSUE THREAD

**Issue by SharonGrossman** [Eywek/typoa#15]
Heya, been using typoa for a while now (due to the codegen that supports anyOf schema definition, very nice!)
I wanted to ask how would you implement OAuth, for example in tsoa it's only used in the decorator @Security('oauth'), would want your input about implementation here

Thanks!

**Comment by Eywek** [comment]
Hello,

Thank you for using this library.

For security you can use the `Security` decorator as well: 
https://github.com/Eywek/typoa/blob/e78515e9109ff82d122879d0757a0bdde4a91810/example/controller.ts#L38

Implement the security middleware factory like here:
https://github.com/Eywek/typoa/blob/e78515e9109ff82d122879d0757a0bdde4a91810/example/security.ts#L1-L5

And configure the security middleware factory in the configuration:
https://github.com/Eywek/typoa/blob/e78515e9109ff82d122879d0757a0bdde4a91810/example/generate.ts#L26

Note: the argument the decorator receive is the argument the security middleware factory will receive (e.g. `scopes`).
