### ISSUE TITLE
support pre / post middlewares

### ISSUE THREAD

**Issue by SharonGrossman** [Eywek/typoa#16]
Hey, I've been using tsoa & typoa in sort of a mix and wanted to know if it's possible to add support of tsoa's 'PreMiddleware' capability to the generated clients
It's coming very handy in adding headers, and in general intercepting requests.
Thanks!

**Comment by Eywek** [comment]
That's a great idea, why did you close the issue?

**Comment by SharonGrossman** [comment]
I realized it's a feature that the codegen library needs to add, am I wrong? Opened it there as a feature request
